### ISSUE TITLE
Fails when creating json.back: Not a valid windows filename

### ISSUE THREAD

**Issue by dartrax** [extiverse/helper#1]
When I do:
`C:\xampp\htdocs\flarum_extiverse_helper> php extiverse upgrade --path C:\xampp\htdocs\flarum`
I get:
```
In Local.php line 135:

  file_put_contents(C:\xampp\htdocs\flarum\composer.json.back-2020-12-24T18:05:16+00:00):
  failed to open stream: No such file or directory

```

I think the filename `composer.json.back-2020-12-24T18:05:16+00:00` that it tries to create is not a valid windows filename because it contains `:`

**Comment by luceos** [comment]
Fixed in upcoming release.
